---
driver:
  name: docker
  hostname: ntp.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: ntp
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - ntp
  pillars:
    top.sls:
      base:
        "*":
          - ntp

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: client
    provisioner:
      pillars-from-files:
        ntp.sls: tests/pillar/client.sls

  - name: server
    provisioner:
      pillars-from-files:
        ntp.sls: tests/pillar/server.sls

  - name: client_auth
    provisioner:
      pillars-from-files:
        ntp.sls: tests/pillar/client_auth.sls

  - name: server_auth
    provisioner:
      pillars-from-files:
        ntp.sls: tests/pillar/server_auth.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
